import { MainModel } from "../models/main-model";
import { ViewModel } from "qtk";
export declare class MainViewModel extends ViewModel {
    model: MainModel;
    nonameIndex: number;
    static EVT_DOC_NEW: string;
    static EVT_DOC_OPEN: string;
    static EVT_DOC_RENAME: string;
    protected models: Array<MainModel>;
    constructor(model: MainModel);
    addModel(model: MainModel): void;
    removeModel(model: MainModel): boolean;
    protected findModel(docName: string): MainModel;
    protected initCommands(): void;
    private registerDelegateCommand(name, exec, canExec);
    countSelectedWidget(): number;
    copy(): void;
    cut(): void;
    paste(): void;
    del(): void;
    canDelete(): boolean;
    canCopy(): boolean;
    canCut(): boolean;
    canPaste(): boolean;
    undo(): boolean;
    redo(): boolean;
    canUndo(): boolean;
    canRedo(): boolean;
    getDocName(): string;
    getDocList(): Array<string>;
    genNoName(): string;
    isNoName(docName: string): boolean;
    newDoc(): boolean;
    saveDoc(docName: string): boolean;
    openDoc(docName: string): boolean;
    removeDoc(docName: string): boolean;
    canAlign(): boolean;
    alignMiddle(): boolean;
    alignCenter(): boolean;
    alignLeft(): boolean;
    alignTop(): boolean;
    alignRight(): boolean;
    alignBottom(): boolean;
    alignToSameWidth(): boolean;
    alignToSameHeight(): boolean;
    canDistribute(): boolean;
    alignDistH(): boolean;
    alignDistV(): boolean;
    static create(model: MainModel): MainViewModel;
}
